// Emits prisma/schema.prisma with the datasource provider matching
// DATABASE_URL (sqlite for `file:` URLs, postgresql otherwise).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const prismaDir = path.join(here, '..', 'prisma');

// Load repo-root .env if DATABASE_URL isn't already set
if (!process.env.DATABASE_URL) {
  for (let dir = path.join(here, '..'), i = 0; i < 5; i++, dir = path.dirname(dir)) {
    const envPath = path.join(dir, '.env');
    if (existsSync(envPath)) {
      for (const line of readFileSync(envPath, 'utf8').split('\n')) {
        const m = line.match(/^DATABASE_URL=(.*)$/);
        if (m) process.env.DATABASE_URL = m[1].trim();
      }
      break;
    }
  }
}

const url = process.env.DATABASE_URL || 'file:./dev.db';
const provider = url.startsWith('file:') ? 'sqlite' : 'postgresql';

const body = readFileSync(path.join(prismaDir, 'schema.body.prisma'), 'utf8');
const header = `// GENERATED by scripts/gen-schema.mjs — edit schema.body.prisma instead.
datasource db {
  provider = "${provider}"
  url      = env("DATABASE_URL")
}

`;
writeFileSync(path.join(prismaDir, 'schema.prisma'), header + body);

// Prisma CLI reads .env next to the schema, not the monorepo root —
// emit the derived DATABASE_URL there (gitignored).
writeFileSync(path.join(prismaDir, '.env'), `DATABASE_URL=${url}\n`);
console.log(`prisma/schema.prisma generated (provider: ${provider})`);
